# Generated by Django 3.2.5 on 2023-07-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KisiselBilgiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('dogum_tarihi', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('adres', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Experiance',
            new_name='Deneyim',
        ),
        migrations.RenameModel(
            old_name='Education',
            new_name='Egitim',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
