# Generated by Django 3.2.5 on 2023-07-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0008_auto_20230715_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='dil',
            name='sertifika',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
