# Generated by Django 3.2.5 on 2023-07-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0009_dil_sertifika'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deneyim',
            old_name='görev',
            new_name='gorev',
        ),
    ]
