# Generated by Django 3.2.5 on 2023-07-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_auto_20230712_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='deneyim',
            old_name='tarih',
            new_name='baslangic_tarihi',
        ),
        migrations.RenameField(
            model_name='egitim',
            old_name='tarih',
            new_name='baslangic_tarihi',
        ),
        migrations.AddField(
            model_name='deneyim',
            name='bitis_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egitim',
            name='bitis_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kisiselbilgiler',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kisiselbilgiler',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kisiselbilgiler',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kisiselbilgiler',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kisiselbilgiler',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kisiselbilgiler',
            name='bilinen_diller',
            field=models.ManyToManyField(to='resumeapp.Dil'),
        ),
    ]
