# Generated by Django 3.2.5 on 2023-07-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_auto_20230712_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisiselbilgiler',
            name='meslek',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
