# Generated by Django 3.2.5 on 2023-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0007_auto_20230714_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deneyim',
            old_name='baslik',
            new_name='görev',
        ),
        migrations.RenameField(
            model_name='egitim',
            old_name='baslik',
            new_name='okul',
        ),
        migrations.RemoveField(
            model_name='kisiselbilgiler',
            name='bilinen_diller',
        ),
        migrations.AddField(
            model_name='dil',
            name='seviye',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dil',
            name='ad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
