# Generated by Django 3.2.5 on 2023-07-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0010_rename_görev_deneyim_gorev'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisiselbilgiler',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
